server:
 port: 8989
spring:
 zipkin:
  base-url: http://localhost:9411
 application:
  name: service-miya

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8770/eureka
