server:
  port: 8861
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  profiles: docker
  application:
   name: eureka-server
