eureka:
 client:
  serviceUrl:
   defaultZone: http://peer1:8761/eureka/,http://peer2:8770/eureka/
#   defaultZone: http://192.168.99.100:8861/eureka/
server:
 port: 8762
spring:
 application:
  name: service-hi
 zipkin:
  base-url: http://localhost:9411
