foo: error-config-update-3
server:
  port: 8881
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8770/eureka/
spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
    bus:
      trace:
        enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
